#!/bin/bash
#echo "Agus Edy Cahyono G.211.13.0047"
OPTIONS="Suhu GPIO Ram Disk Alive MyIP Quit"
select opt in $OPTIONS; do
	if [ "$opt" = "Quit" ]; then
		echo done
		exit
	
	elif [ "$opt" = "Suhu" ]; then
		#echo Ping Masukan IP:
		#read IP
		#ping -c5 $IP
		vcgencmd measure_temp 
		#clear	

	elif [ "$opt" = "GPIO" ]; then
                #echo Trace Path:
		#read PTH
		#tracepath $PTH
		gpio readall

	elif [ "$opt" = "Ram" ]; then
                #echo Ns Lookup Masukan Alamat:
		#read ADDR
		#nslookup $ADDR
		free -h

	elif [ "$opt" = "Disk" ]; then
                df -h

	elif [ "$opt" = "Alive" ]; then
		#sudo arp-scan -l --interface=eth0
                sudo arp-scan -l --interface=eth0

	elif [ "$opt" = "MyIP" ]; then
		ifconfig
 	
	else
		clear
		echo bad option
	fi
done
